# Generated by Django 4.0 on 2023-06-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('file_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('void', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('blobs', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('edges', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('mean_bn', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('mean_bs', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('mean_h', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('mean_l', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('mean_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('stdev_bn', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('stdev_bs', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('stdev_h', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('stdev_l', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('stdev_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('bicyclist_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('bicyclist_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('building_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('building_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('car_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('car_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('fence_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('fence_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('pavement_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('pavement_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('pedestrian_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('pedestrian_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('pole_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('pole_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('road_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('road_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('signSymbol_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('signSymbol_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('sky_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('sky_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('tree_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('tree_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('unlabelled_n', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('unlabelled_s', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_bench', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_bicycle', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_boat', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_bus', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_car', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_chair', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_fire_hydrant', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_motorcycle', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_person', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_potted_plant', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_stop_sign', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_traffic_light', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_train', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_truck', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('od_umbrella', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
            ],
        ),
    ]
